-- Admin RBAC, login audit fields, and operation audit log.
-- Safe to run on an existing KingbaseES/PostgreSQL-compatible schema.

do $$
declare
  v_constraint_name text;
begin
  select c.conname
    into v_constraint_name
  from pg_constraint c
  join pg_class t on t.oid = c.conrelid
  where t.relname = 'sys_user'
    and c.contype = 'c'
    and pg_get_constraintdef(c.oid) like '%role%'
  limit 1;

  if v_constraint_name is not null then
    execute 'alter table sys_user drop constraint ' || quote_ident(v_constraint_name);
  end if;
end $$;

alter table sys_user
  add constraint sys_user_role_check
  check (role in ('user', 'doctor', 'admin', 'super_admin'));

do $$
declare
  v_constraint_name text;
begin
  select c.conname
    into v_constraint_name
  from pg_constraint c
  join pg_class t on t.oid = c.conrelid
  where t.relname = 'sys_user'
    and c.contype = 'c'
    and pg_get_constraintdef(c.oid) like '%status%'
  limit 1;

  if v_constraint_name is not null then
    execute 'alter table sys_user drop constraint ' || quote_ident(v_constraint_name);
  end if;
end $$;

alter table sys_user
  add constraint sys_user_status_check
  check (status in ('active', 'disabled', 'locked'));

alter table sys_user
  add column if not exists last_login_ip varchar(64);

create table if not exists admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_user_id bigint references sys_user(id) on delete set null,
  action varchar(64) not null,
  target_type varchar(64) not null,
  target_id bigint,
  before_json jsonb,
  after_json jsonb,
  ip_address varchar(64),
  user_agent varchar(500),
  created_at timestamp not null default current_timestamp
);

create index if not exists idx_admin_audit_log_admin_time
  on admin_audit_log(admin_user_id, created_at desc);

create index if not exists idx_admin_audit_log_target
  on admin_audit_log(target_type, target_id);
