alter table sys_user
  add column if not exists token_version int not null default 0,
  add column if not exists password_changed_at timestamp,
  add column if not exists last_login_ip varchar(64);

alter table user_profile
  add column if not exists fasting_glucose numeric(5,2),
  add column if not exists postprandial_glucose numeric(5,2),
  add column if not exists hba1c numeric(4,2),
  add column if not exists hometown varchar(24),
  add column if not exists city varchar(24),
  add column if not exists occupation varchar(24),
  add column if not exists medication_status varchar(128);

alter table user_profile
  alter column diagnosed_diabetes drop not null;

create table if not exists user_privacy_settings (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references sys_user(id) on delete cascade,
  health_reminder_enabled boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table if not exists user_data_authorizations (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references sys_user(id) on delete cascade,
  health_data_analysis_authorized boolean not null default true,
  assistant_context_authorized boolean not null default true,
  plan_suggestion_authorized boolean not null default true,
  news_recommendation_authorized boolean not null default true,
  policy_version varchar(32) not null default 'v1.0',
  granted_at timestamp,
  withdrawn_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create index if not exists idx_user_data_authorizations_user
  on user_data_authorizations(user_id);

create table if not exists user_data_authorization_logs (
  id bigint generated by default as identity primary key,
  user_id bigint not null references sys_user(id) on delete cascade,
  action varchar(32) not null check (action in ('grant', 'revoke', 'withdraw_all', 'update')),
  scope varchar(32) not null check (scope in ('master', 'assistant_context', 'plan_suggestion', 'news_recommendation')),
  old_value boolean,
  new_value boolean,
  policy_version varchar(32),
  source varchar(32) not null default 'system',
  reason varchar(64),
  ip_address varchar(64),
  user_agent varchar(500),
  created_at timestamp not null default current_timestamp
);

create index if not exists idx_user_data_authorization_logs_user_time
  on user_data_authorization_logs(user_id, created_at desc);

create table if not exists auth_security_log (
  id bigint generated by default as identity primary key,
  user_id bigint not null references sys_user(id) on delete cascade,
  action varchar(64) not null,
  ip_address varchar(64),
  user_agent varchar(500),
  created_at timestamp not null default current_timestamp
);

create index if not exists idx_auth_security_log_user_time
  on auth_security_log(user_id, created_at desc);

create table if not exists uploaded_file (
  id bigint generated by default as identity primary key,
  file_id varchar(64) not null unique,
  user_id bigint not null references sys_user(id) on delete cascade,
  biz_type varchar(32) not null,
  file_name varchar(255) not null,
  stored_name varchar(255) not null,
  mime_type varchar(128),
  size_bytes bigint not null default 0,
  storage_path varchar(500) not null,
  created_at timestamp not null default current_timestamp
);

create index if not exists idx_uploaded_file_user_time
  on uploaded_file(user_id, created_at desc);
