-- KingbaseES / PostgreSQL-compatible initial schema.
-- This file is intentionally not executed by the Express app.

create table if not exists sys_user (
    id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    phone varchar(32) unique,
    email varchar(128) unique,
    password_hash varchar(255) not null,
    role varchar(32) not null check (role in ('user', 'admin', 'doctor')),
    status varchar(32) not null check (status in ('active', 'disabled')),
    nickname varchar(64),
    avatar_url varchar(500),
    last_login_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    deleted_at timestamp
);

create table if not exists user_consent (
    id bigint generated by default as identity primary key,
    user_id bigint not null references sys_user(id),
    consent_type varchar(32) not null check (consent_type in ('privacy', 'ai_disclaimer', 'health_data')),
    version varchar(32) not null,
    accepted boolean not null,
    accepted_at timestamp,
    ip_address varchar(64),
    user_agent varchar(500),
    created_at timestamp not null default current_timestamp
);

create index if not exists idx_user_consent_user on user_consent(user_id);

create table if not exists user_profile (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references sys_user(id),
    gender varchar(16) check (gender in ('male', 'female')),
    birth_date date,
    age_snapshot int check (age_snapshot between 0 and 120),
    height_cm numeric(5,2) check (height_cm between 80 and 250),
    weight_kg numeric(5,2) check (weight_kg between 20 and 300),
    bmi numeric(5,2) check (bmi between 5 and 100),
    waist_cm numeric(5,2) check (waist_cm between 30 and 200),
    sbp_mm_hg int check (sbp_mm_hg between 60 and 260),
    dbp_mm_hg int check (dbp_mm_hg between 30 and 180),
    family_history_diabetes boolean,
    diagnosed_diabetes boolean not null default false,
    diabetes_type varchar(32) check (diabetes_type in ('type1', 'type2', 'gestational', 'special', 'unknown')),
    past_history jsonb,
    allergy varchar(500),
    lifestyle jsonb,
    emergency_contact varchar(64),
    emergency_phone varchar(32),
    updated_at timestamp not null default current_timestamp,
    created_at timestamp not null default current_timestamp
);

create table if not exists health_measurement (
    id bigint generated by default as identity primary key,
    user_id bigint not null references sys_user(id),
    source varchar(32) not null check (source in ('manual', 'report', 'checkin')),
    measured_at timestamp not null,
    height_cm numeric(5,2) check (height_cm between 80 and 250),
    weight_kg numeric(5,2) check (weight_kg between 20 and 300),
    bmi numeric(5,2) check (bmi between 5 and 100),
    waist_cm numeric(5,2) check (waist_cm between 30 and 200),
    sbp_mm_hg int check (sbp_mm_hg between 60 and 260),
    dbp_mm_hg int check (dbp_mm_hg between 30 and 180),
    fasting_glucose numeric(5,2),
    postprandial_glucose numeric(5,2),
    hba1c numeric(4,2),
    note varchar(500),
    created_at timestamp not null default current_timestamp
);

create index if not exists idx_health_measurement_user_time on health_measurement(user_id, measured_at desc);

create table if not exists risk_assessment (
    id bigint generated by default as identity primary key,
    user_id bigint not null references sys_user(id),
    profile_snapshot jsonb not null,
    diagnosed_diabetes boolean not null,
    diabetes_type varchar(32) check (diabetes_type in ('type1', 'type2', 'gestational', 'special', 'unknown')),
    score int check (score between 0 and 51),
    score_status varchar(32) not null check (score_status in ('complete', 'incomplete', 'not_applicable', 'diagnosed')),
    score_rule_version varchar(32) not null default 'cdrs_2024_v1',
    missing_fields jsonb,
    risk_level varchar(32) check (risk_level in ('low', 'high', 'diagnosed')),
    is_high_risk boolean,
    score_detail jsonb,
    abnormal_indicators jsonb,
    advice_summary text,
    advice_json jsonb,
    status varchar(32) not null check (status in ('draft', 'processing', 'succeeded', 'failed')),
    request_id varchar(128),
    idempotency_key varchar(128),
    dify_workflow_run_id varchar(128),
    error_message text,
    created_at timestamp not null default current_timestamp
);

create index if not exists idx_risk_assessment_user_time on risk_assessment(user_id, created_at desc);
create index if not exists idx_risk_assessment_level on risk_assessment(risk_level);
create unique index if not exists uk_risk_assessment_idem on risk_assessment(user_id, idempotency_key);

create table if not exists doctor (
    id bigint generated by default as identity primary key,
    name varchar(64) not null,
    title varchar(64),
    department varchar(64),
    specialty varchar(255),
    intro text,
    avatar_url varchar(500),
    online_status varchar(32) not null check (online_status in ('online', 'offline')),
    display_status varchar(32) not null check (display_status in ('published', 'hidden')),
    sort_order int not null default 0,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    deleted_at timestamp
);

create table if not exists article_category (
    id bigint generated by default as identity primary key,
    name varchar(64) not null,
    code varchar(64) unique,
    sort_order int not null default 0,
    status varchar(32) not null check (status in ('published', 'hidden'))
);

create table if not exists article (
    id bigint generated by default as identity primary key,
    category_id bigint references article_category(id),
    title varchar(200) not null,
    summary varchar(500),
    content text not null,
    cover_url varchar(500),
    tags jsonb,
    author varchar(64),
    view_count int not null default 0,
    recommend_weight int not null default 0,
    status varchar(32) not null check (status in ('draft', 'published', 'offline')),
    published_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    deleted_at timestamp
);

create index if not exists idx_article_category on article(category_id);
create index if not exists idx_article_status_time on article(status, published_at desc);

create table if not exists diabetes_type_info (
    id bigint generated by default as identity primary key,
    type_code varchar(32) unique check (type_code in ('type1', 'type2', 'gestational', 'special')),
    name varchar(64) not null,
    cover_url varchar(500),
    pathogenesis text,
    clinical_features text,
    treatment text,
    sort_order int not null default 0,
    status varchar(32) not null check (status in ('published', 'hidden'))
);

create table if not exists lifestyle_plan (
    id bigint generated by default as identity primary key,
    user_id bigint not null references sys_user(id),
    risk_assessment_id bigint references risk_assessment(id),
    title varchar(128) not null,
    goal_summary text,
    status varchar(32) not null check (status in ('draft', 'active', 'archived', 'failed')),
    start_date date,
    end_date date,
    preferences jsonb,
    plan_json jsonb not null,
    dify_workflow_run_id varchar(128),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create index if not exists idx_lifestyle_plan_user_status on lifestyle_plan(user_id, status);

create table if not exists plan_task (
    id bigint generated by default as identity primary key,
    plan_id bigint not null references lifestyle_plan(id),
    task_type varchar(32) not null check (task_type in ('diet', 'exercise', 'water', 'sleep', 'glucose', 'review')),
    title varchar(128) not null,
    description text,
    target_value numeric(8,2),
    unit varchar(32),
    target_time varchar(64),
    weekdays varchar(32),
    sort_order int not null default 0,
    metadata jsonb,
    created_at timestamp not null default current_timestamp
);

create index if not exists idx_plan_task_plan on plan_task(plan_id);

create table if not exists checkin_record (
    id bigint generated by default as identity primary key,
    user_id bigint not null references sys_user(id),
    plan_id bigint references lifestyle_plan(id),
    checkin_date date not null,
    completion_rate numeric(5,2) check (completion_rate between 0 and 100),
    ai_summary text,
    ai_advice text,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    unique(user_id, checkin_date)
);

create index if not exists idx_checkin_record_user_date on checkin_record(user_id, checkin_date desc);

create table if not exists checkin_item (
    id bigint generated by default as identity primary key,
    checkin_record_id bigint not null references checkin_record(id),
    plan_task_id bigint references plan_task(id),
    task_type varchar(32) not null check (task_type in ('diet', 'exercise', 'water', 'sleep', 'glucose', 'review')),
    planned_value numeric(8,2),
    actual_value numeric(8,2),
    unit varchar(32),
    status varchar(32) not null check (status in ('pending', 'done', 'partial', 'missed')),
    detail_text text,
    metadata jsonb,
    created_at timestamp not null default current_timestamp
);

create index if not exists idx_checkin_item_record on checkin_item(checkin_record_id);

create table if not exists health_analysis_report (
    id bigint generated by default as identity primary key,
    user_id bigint not null references sys_user(id),
    period_start date not null,
    period_end date not null,
    completion_rate numeric(5,2) check (completion_rate between 0 and 100),
    summary text,
    advice text,
    analysis_json jsonb not null,
    dify_workflow_run_id varchar(128),
    created_at timestamp not null default current_timestamp
);

create index if not exists idx_health_analysis_user_period on health_analysis_report(user_id, period_start desc, period_end desc);

create table if not exists ai_conversation (
    id bigint generated by default as identity primary key,
    user_id bigint not null references sys_user(id),
    app_type varchar(32) not null check (app_type in ('assistant', 'doctor')),
    doctor_id bigint references doctor(id),
    dify_conversation_id varchar(128),
    title varchar(128),
    status varchar(32) not null check (status in ('active', 'closed')),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create index if not exists idx_ai_conversation_user_type on ai_conversation(user_id, app_type, updated_at desc);

create table if not exists ai_message (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null references ai_conversation(id),
    role varchar(32) not null check (role in ('user', 'assistant', 'system')),
    content text not null,
    dify_message_id varchar(128),
    metadata jsonb,
    created_at timestamp not null default current_timestamp
);

create index if not exists idx_ai_message_conversation_time on ai_message(conversation_id, created_at asc);

create table if not exists dify_run_log (
    id bigint generated by default as identity primary key,
    user_id bigint references sys_user(id),
    app_code varchar(64) not null,
    app_type varchar(32) not null check (app_type in ('workflow', 'chatflow')),
    request_id varchar(128),
    workflow_run_id varchar(128),
    task_id varchar(128),
    conversation_id varchar(128),
    inputs jsonb,
    outputs jsonb,
    status varchar(32) not null check (status in ('running', 'succeeded', 'failed', 'paused')),
    elapsed_time numeric(10,3),
    total_tokens int,
    error_message text,
    created_at timestamp not null default current_timestamp
);

create index if not exists idx_dify_run_log_user_time on dify_run_log(user_id, created_at desc);
create index if not exists idx_dify_run_log_request on dify_run_log(request_id);
