-- Persisted user content interactions and plan-task completion helpers.

alter table system_message
  add column if not exists message_key varchar(128),
  add column if not exists updated_at timestamp not null default current_timestamp;

create unique index if not exists uk_system_message_user_key
  on system_message(user_id, message_key);

comment on column system_message.message_key is 'Deterministic key for generated business messages so read status can survive content refresh.';

create table if not exists article_like (
  id bigint generated by default as identity primary key,
  user_id bigint not null references sys_user(id) on delete cascade,
  article_id bigint not null references article(id) on delete cascade,
  created_at timestamp not null default current_timestamp,
  unique(user_id, article_id)
);

create index if not exists idx_article_like_user_time
  on article_like(user_id, created_at desc);

create table if not exists article_comment (
  id bigint generated by default as identity primary key,
  article_id bigint not null references article(id) on delete cascade,
  user_id bigint not null references sys_user(id) on delete cascade,
  parent_id bigint references article_comment(id) on delete cascade,
  content text not null,
  like_count bigint not null default 0,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  deleted_at timestamp
);

create index if not exists idx_article_comment_article_time
  on article_comment(article_id, created_at desc);

create table if not exists article_comment_like (
  id bigint generated by default as identity primary key,
  user_id bigint not null references sys_user(id) on delete cascade,
  comment_id bigint not null references article_comment(id) on delete cascade,
  created_at timestamp not null default current_timestamp,
  unique(user_id, comment_id)
);

create index if not exists idx_article_comment_like_user_time
  on article_comment_like(user_id, created_at desc);

create unique index if not exists uk_checkin_item_record_plan_task
  on checkin_item(checkin_record_id, plan_task_id)
  where plan_task_id is not null;
