-- Doctor profile extensions and consultation work orders.

alter table doctor
  add column if not exists user_id bigint references sys_user(id) on delete set null,
  add column if not exists license_no varchar(128),
  add column if not exists profile_md text,
  add column if not exists consult_status varchar(32) not null default 'online',
  add column if not exists audit_status varchar(32) not null default 'approved',
  add column if not exists reviewed_by bigint references sys_user(id) on delete set null,
  add column if not exists reviewed_at timestamp;

do $$
declare
  v_constraint_name text;
begin
  select c.conname
    into v_constraint_name
  from pg_constraint c
  join pg_class t on t.oid = c.conrelid
  where t.relname = 'doctor'
    and c.contype = 'c'
    and pg_get_constraintdef(c.oid) like '%consult_status%'
  limit 1;

  if v_constraint_name is not null then
    execute 'alter table doctor drop constraint ' || quote_ident(v_constraint_name);
  end if;
end $$;

alter table doctor
  add constraint doctor_consult_status_check
  check (consult_status in ('online', 'offline', 'paused'));

do $$
declare
  v_constraint_name text;
begin
  select c.conname
    into v_constraint_name
  from pg_constraint c
  join pg_class t on t.oid = c.conrelid
  where t.relname = 'doctor'
    and c.contype = 'c'
    and pg_get_constraintdef(c.oid) like '%audit_status%'
  limit 1;

  if v_constraint_name is not null then
    execute 'alter table doctor drop constraint ' || quote_ident(v_constraint_name);
  end if;
end $$;

alter table doctor
  add constraint doctor_audit_status_check
  check (audit_status in ('pending_review', 'approved', 'rejected'));

comment on column doctor.online_status is 'Deprecated display online flag kept for compatibility. Prefer doctor.consult_status for consultation availability.';
comment on column doctor.consult_status is 'Consultation availability: online, offline, or paused.';
comment on column doctor.display_status is 'User-facing publication state: published or hidden.';
comment on column doctor.audit_status is 'Back-office review state: pending_review, approved, or rejected.';

create table if not exists consultation_order (
  id bigint generated by default as identity primary key,
  user_id bigint not null references sys_user(id) on delete cascade,
  doctor_id bigint not null references doctor(id) on delete restrict,
  conversation_id bigint references ai_conversation(id) on delete set null,
  status varchar(32) not null check (status in ('open', 'waiting_admin', 'answered', 'closed')),
  title varchar(128),
  summary text,
  priority varchar(32) not null default 'normal' check (priority in ('normal', 'urgent')),
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create index if not exists idx_consultation_order_user_time
  on consultation_order(user_id, created_at desc);

create index if not exists idx_consultation_order_status
  on consultation_order(status, updated_at desc);

create table if not exists consultation_attachment (
  id bigint generated by default as identity primary key,
  consultation_id bigint not null references consultation_order(id) on delete cascade,
  uploader_id bigint references sys_user(id) on delete set null,
  file_url varchar(500) not null,
  file_name varchar(255),
  file_type varchar(128),
  file_size bigint,
  created_at timestamp not null default current_timestamp
);

create index if not exists idx_consultation_attachment_order
  on consultation_attachment(consultation_id, created_at desc);
