-- Article administration fields, favorites, and read logs.

alter table article
  add column if not exists author_user_id bigint references sys_user(id) on delete set null,
  add column if not exists content_md text,
  add column if not exists content_html text,
  add column if not exists audit_status varchar(32) not null default 'approved',
  add column if not exists reviewed_by bigint references sys_user(id) on delete set null,
  add column if not exists reviewed_at timestamp,
  add column if not exists reject_reason text,
  add column if not exists like_count bigint not null default 0,
  add column if not exists favorite_count bigint not null default 0;

do $$
declare
  v_constraint_name text;
begin
  select c.conname
    into v_constraint_name
  from pg_constraint c
  join pg_class t on t.oid = c.conrelid
  where t.relname = 'article'
    and c.contype = 'c'
    and pg_get_constraintdef(c.oid) like '%audit_status%'
  limit 1;

  if v_constraint_name is not null then
    execute 'alter table article drop constraint ' || quote_ident(v_constraint_name);
  end if;
end $$;

alter table article
  add constraint article_audit_status_check
  check (audit_status in ('pending_review', 'approved', 'rejected'));

update article
set audit_status = 'pending_review'
where status = 'draft';

update article
set audit_status = 'approved'
where status in ('published', 'offline');

comment on column article.content is 'Article canonical body. For Markdown articles this stores Markdown text; content_html may cache rendered HTML.';
comment on column article.content_md is 'Deprecated compatibility alias for Markdown body. Prefer article.content.';
comment on column article.content_html is 'Optional rendered HTML cache generated from article.content.';

create table if not exists article_favorite (
  id bigint generated by default as identity primary key,
  user_id bigint not null references sys_user(id) on delete cascade,
  article_id bigint not null references article(id) on delete cascade,
  created_at timestamp not null default current_timestamp,
  unique(user_id, article_id)
);

create index if not exists idx_article_favorite_user_time
  on article_favorite(user_id, created_at desc);

create table if not exists article_read_log (
  id bigint generated by default as identity primary key,
  user_id bigint references sys_user(id) on delete set null,
  article_id bigint not null references article(id) on delete cascade,
  ip_address varchar(64),
  created_at timestamp not null default current_timestamp
);

create index if not exists idx_article_read_log_article_time
  on article_read_log(article_id, created_at desc);
