-- Persistent messages and homepage operation slots.

create table if not exists system_message (
  id bigint generated by default as identity primary key,
  user_id bigint references sys_user(id) on delete cascade,
  type varchar(32) not null check (type in ('archive', 'risk', 'plan', 'assistant', 'consultation', 'system')),
  title varchar(128) not null,
  content text,
  route_name varchar(64),
  payload jsonb,
  read_at timestamp,
  created_at timestamp not null default current_timestamp
);

comment on column system_message.type is 'Business message type. Frontend message group is derived separately: archive/risk/system -> service, plan/consultation -> reminder, assistant -> assistant.';

create index if not exists idx_system_message_user_time
  on system_message(user_id, created_at desc);

create table if not exists home_operation_config (
  id bigint generated by default as identity primary key,
  slot_code varchar(64) not null check (slot_code in ('home_banner', 'hot_articles', 'recommended_doctors')),
  target_type varchar(64) not null check (target_type in ('article', 'doctor', 'diabetes_type')),
  target_id bigint,
  title varchar(128),
  sort_order int not null default 0,
  status varchar(32) not null check (status in ('active', 'hidden')),
  start_at timestamp,
  end_at timestamp,
  created_by bigint references sys_user(id) on delete set null,
  created_at timestamp not null default current_timestamp
);

create index if not exists idx_home_operation_slot
  on home_operation_config(slot_code, status, sort_order);
